using System.Collections.Concurrent;
using Fleck;
using StackExchange.Redis;

namespace Api;

public class ConnectionManager(IDatabase redis)
{
    /// <summary>
    /// the string key is the unique socket ID generated by the client
    /// </summary>
    public ConcurrentDictionary<string, IWebSocketConnection> Sockets { get; set; } = new();
    
    private const string TOPIC_PREFIX = "topic:";
    private const string CONNECTION_TO_TOPICS = "connection:topics:";
    
    public const string TOPIC_AUTHENTICATED = "authenticated";
    public static string TOPIC_CHAT_ROOM(string roomId) => $"chat:room:{roomId}";

    public async Task Subscribe(IWebSocketConnection socket, string topic, string clientGeneratedConnectionId)
    {
        var topicKey = $"{TOPIC_PREFIX}{topic}";
        var connectionTopicsKey = $"{CONNECTION_TO_TOPICS}{clientGeneratedConnectionId}";

        var tx = redis.CreateTransaction();
        tx.SetAddAsync(topicKey, clientGeneratedConnectionId);
        tx.KeyExpireAsync(topicKey, TimeSpan.FromDays(1));
        
        tx.SetAddAsync(connectionTopicsKey, topic);
        tx.KeyExpireAsync(connectionTopicsKey, TimeSpan.FromDays(1));
        
        await tx.ExecuteAsync();
    }

    public Task<bool> OnOpen(IWebSocketConnection socket, string clientGeneratedConnectionId)
    {
        if (Sockets.TryGetValue(clientGeneratedConnectionId, out var existingSocket))
        {
            try { existingSocket.Close(); } catch { }
        }
        
        return Task.FromResult(Sockets.TryAdd(clientGeneratedConnectionId, socket));
    }

    public async Task Unsubscribe(IWebSocketConnection socket, string topic)
    {
        var customConnectionId = socket.ConnectionInfo.Id.ToString();
        
        await redis.SetRemoveAsync($"{TOPIC_PREFIX}{topic}", customConnectionId);
        await redis.SetRemoveAsync($"{CONNECTION_TO_TOPICS}{customConnectionId}", topic);
    }

    public async Task OnClose(IWebSocketConnection socket, string clientGeneratedConnectionId)
    {
        Sockets.TryRemove(clientGeneratedConnectionId, out _);
        
        var topics = await redis.SetMembersAsync($"{CONNECTION_TO_TOPICS}{clientGeneratedConnectionId}");
        
        var tx = redis.CreateTransaction();
        foreach (var topic in topics)
        {
            tx.SetRemoveAsync($"{TOPIC_PREFIX}{topic}", clientGeneratedConnectionId);
        }
        tx.KeyDeleteAsync($"{CONNECTION_TO_TOPICS}{clientGeneratedConnectionId}");
        
        await tx.ExecuteAsync();
    }

    public async Task BroadcastToAllTopicSubscribers(string topic, string message)
    {
        var subscribers = await redis.SetMembersAsync($"{TOPIC_PREFIX}{topic}");
        
        foreach (var subscriberId in subscribers)
        {
            if (Sockets.TryGetValue(subscriberId.ToString(), out var socket))
            {
                await socket.Send(message);
            }
        }
    }
}